### ISSUE TITLE
名人推薦

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/psyche#13]
1.添加按鈕
![image](https://cloud.githubusercontent.com/assets/4414580/6363417/d6502164-bcd3-11e4-95cf-300eae64ae4b.png)

2.內容 右方名人欄 底的灰色塊 要延伸至底
![image](https://cloud.githubusercontent.com/assets/4414580/6363428/fc67faf2-bcd3-11e4-9280-84c9f105e7ab.png)

**Comment by maysheena** [comment]
添加按鈕的部分是不是有更清楚地檔案呢？

**Comment by fdjkgh580** [comment]
@maysheena 按鈕我這邊做好了~~~

**Comment by fdjkgh580** [comment]
@maysheena 這邊內文的樣式，是不是行高有稍微拉高一點呢？我看目前比較貼緊
![image](https://cloud.githubusercontent.com/assets/4414580/6374034/3f25f4be-bd49-11e4-990d-f0e499b2a309.png)

**Comment by maysheena** [comment]
已經修改囉！
