### ISSUE TITLE
紅利專區

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/psyche#15]
1.
![image](https://cloud.githubusercontent.com/assets/4414580/6363468/a6c50bde-bcd4-11e4-8fc3-7b5fba921d0b.png)

※格式如同產品總攬品名的行距 / 規格點數的位置、行距同產品總攬 (OK
※右上角購物車 icon 右側多一樣的箭頭圓 icon 顯示還有多少點數 (我添加了位置，剩下樣式)

**Comment by maysheena** [comment]
已經添加完成囉！

**Comment by fdjkgh580** [comment]
歪掉中XD ㄧ要這樣喔
![image](https://cloud.githubusercontent.com/assets/4414580/6375688/b3e37fe2-bd53-11e4-82a8-e38047e6c0ac.png)
