### ISSUE TITLE
首頁

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/psyche#16]
1.左主選單
選單文字換能提拉保濕面膜保字到下一行如圖(以調整)
‧底下選單聯絡我們的 f icon 滑鼠移過也要變亮
![image](https://cloud.githubusercontent.com/assets/4414580/6363485/f1f7de2e-bcd4-11e4-87bd-f741b7f77c2c.png)

2.
滑鼠滾動圖會上下跑? 要固定不動如圖(以OK)
![image](https://cloud.githubusercontent.com/assets/4414580/6363494/10715088-bcd5-11e4-86df-aec91044b7bf.png)
點圖加上連結功能到相對單一產品頁面 (OK
●筆電看到的畫面：解析 1366x768

3.

**Comment by maysheena** [comment]
Fb icon 已經換上囉！

**Comment by fdjkgh580** [comment]
@maysheena 幫我推送宜下喔
