### ISSUE TITLE
最新消息

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/psyche#19]
1.
-狀態列和內頁內容相疊一樣問題如下 (上面固定的版面可以加個白色背景)
-滑鼠滾動頁面會上下動這頁應固定不動 (OK
-第幾頁的位置改到如圖點第二頁位置也跑掉
![image](https://cloud.githubusercontent.com/assets/4414580/6363594/25fb60be-bcd6-11e4-9fe0-e298a156402e.png)

2.
- 請用完整案例 2 段文字 2 張圖要看輸入資料後的格式字距行距大小圖大小位
置請參照原設計麻煩了。

![image](https://cloud.githubusercontent.com/assets/4414580/6363611/6015edfa-bcd6-11e4-9958-00b5641eef22.png)

- 內文行距太小請加大
![image](https://cloud.githubusercontent.com/assets/4414580/6363629/92310202-bcd6-11e4-9f68-4c5351ea5210.png)

**Comment by maysheena** [comment]
頁碼  ＆  內文  已經調整囉～
