### ISSUE TITLE
搜尋

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/psyche#20]
1. OK
按搜尋 帳戶.購物 icon 不見 搜尋視窗跳到如圖位置
(我會改成往下移到線的下方)
![image](https://cloud.githubusercontent.com/assets/4414580/6363654/edd43e80-bcd6-11e4-8906-e65e24fdc324.png)

2.
-字編排 bug 品名成一排和兩排 底下規格定價區塊應同高
-底下規格裡 應同單一商品頁面有訂價會員價點數資訊，"產品總攬要修改"
![image](https://cloud.githubusercontent.com/assets/4414580/6363684/27d4f23c-bcd7-11e4-81ae-aa447383fd09.png)

**Comment by maysheena** [comment]
已經修改好囉～

**Comment by fdjkgh580** [comment]
@maysheena OK
