### ISSUE TITLE
聯絡我們

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/psyche#21]
1.
![image](https://cloud.githubusercontent.com/assets/4414580/6363713/7a106676-bcd7-11e4-9fa1-b80178b96110.png)
如圖左上如有疑問…兩行文字上移些
底下服務據點表格資訊上移些

2.
表格內容
。上班時間改成上午 11 點到下午 6 點
。臉書改如圖紅框形式點縮圖和文字皆可連結

3.
![image](https://cloud.githubusercontent.com/assets/4414580/6363724/9bbd2fd4-bcd7-11e4-8c27-d21959d3477e.png)

4.
‧驗證碼有大小寫之份不要有(我後台做)

**Comment by maysheena** [comment]
臉書要如何更改樣式呢？？？

**Comment by fdjkgh580** [comment]
@maysheena 臉書我在喬好了，先不理他XD
