### ISSUE TITLE
購物問題

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/psyche#22]
((剩下第6點 02/25 23:39))

1.OK
![image](https://cloud.githubusercontent.com/assets/4414580/6363736/e19c642a-bcd7-11e4-89ba-54a78dda2ad6.png)
(OK)

2.OK
![image](https://cloud.githubusercontent.com/assets/4414580/6363739/f3b79f3a-bcd7-11e4-854f-5bfb4cf47b7e.png)
(我處理，改連結即可，宜軒會換按鈕圖片 OK)

3.OK
![image](https://cloud.githubusercontent.com/assets/4414580/6363751/12baca1a-bcd8-11e4-800f-7897c00c65f8.png)

4.OK
●結帳流程
 如下圖
‧ 點計算方式回到首頁 bug 這有給你頁面下面紅框
‧ 返回購物 icon 連到紅利點數兌換 bug 應連到產品總覽
‧ icon 前往結帳改成繼續結帳
‧ 下方點紅利專區色塊和跑馬燈商品會連結到紅利專區頁面
 商品列要會動 / 左右箭頭不見了
![image](https://cloud.githubusercontent.com/assets/4414580/6363760/48450132-bcd8-11e4-93ec-1806e8a26781.png)

5.OK
郵局銀行匯款改成 ATM 轉帳匯款
![image](https://cloud.githubusercontent.com/assets/4414580/6363762/5a49a036-bcd8-11e4-8688-58fc7a04bf9f.png)

6
下圖右上購物筆數已結帳完應回到零筆
‧紅框的字：賽姬提醒您~~...，這兩行字級加大 2 個，
並改以下編排：標示深橘色字也照此改
![image](https://cloud.githubusercontent.com/assets/4414580/6363776/73717660-bcd8-11e4-93d5-f10ffde73721.png)

賽姬提醒您：
1. 請於繳費期限內至您鄰近的實體 ATM 完成轉帳付款
2. 回到會員帳戶，訂單列表紀錄頁面，填入匯款後五碼，並按送出，賣家即可
收到您的明細。

![image](https://cloud.githubusercontent.com/assets/4414580/6363782/81b99824-bcd8-11e4-8ffa-2ad6ce4d8cf2.png)

![image](https://cloud.githubusercontent.com/assets/4414580/6363792/a560d760-bcd8-11e4-9ed9-b4c5d3c1cd95.png)

7.OK
訂單列表紀錄
![image](https://cloud.githubusercontent.com/assets/4414580/6363806/cb824000-bcd8-11e4-920d-ef16d2489273.png)

8.OK
![image](https://cloud.githubusercontent.com/assets/4414580/6363811/d8b20b52-bcd8-11e4-93dd-
f98b2c043d07.png)

**Comment by maysheena** [comment]
結帳第三部   不曉得現在已經修改的樣式，是不是上述所改的樣式呢？

注意事項裏的紅字部分是需要添加的嗎？

**Comment by maysheena** [comment]
另外在結帳第一步，我有不小心將按鈕“前往結帳”替換成”結帳“    ，可能還要再請宜軒那裏，覆蓋成原本圖示！

**Comment by fdjkgh580** [comment]
紅字看起來是在跟宜軒討論的東西，不理他囉，現在這樣OK
