### ISSUE TITLE
更改滿額文字

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/psyche#38]
1.
![image](https://cloud.githubusercontent.com/assets/4414580/6429693/4f861a7c-c01f-11e4-9bd7-f032386d5c3c.png)

2.
![image](https://cloud.githubusercontent.com/assets/4414580/6429717/a78dd75e-c020-11e4-848a-a5032e66521c.png)

**Comment by maysheena** [comment]
這裏的話是連同“台灣本島地區訂單購未滿2000.............海外另計。”這段話也要加入嗎？
