### ISSUE TITLE
購物說明文字修改

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/psyche#46]
1.
![image](https://cloud.githubusercontent.com/assets/4414580/6429739/47197fbc-c021-11e4-9fa8-82e93bb3d716.png)

紅框內容改成:台灣本島地區單筆訂購未滿 2000 元、離島地區未滿 3000 元,將依實際貨
運費用收取運費。
本島寄送,消費者需自付運費新台幣 100 元、澎湖 250 元、金門 340 元、馬祖 340 元、海
外另計。

2.
![image](https://cloud.githubusercontent.com/assets/4414580/6429743/7be4e650-c021-11e4-9286-d4ba297ac768.png)
![image](https://cloud.githubusercontent.com/assets/4414580/6429748/9bdaaa58-c021-11e4-9ffb-f5d929e320bc.png)
■ 退換貨須知

根據消費者保護法規定, 商品到貨享 7 天猶豫期之權益(注意!鑑賞期非試用期),辦理退貨商

品必須是全新狀態且包裝完整,否則將會影響退貨權限。

■ 退貨方式

若商品發生新品瑕疵之情形,您可申請更換新品,請透過客服信箱 hanlinpsyche@gmail.com,

我們一定盡速與您聯絡並且替您作退換貨處理。

申請退換貨時請務必將商品完整包裝,配件,贈品,發票等置入原外包裝箱內, 以利退換貨作業。

■ 退貨權限

以下情形恕無法接受退、換貨:

1) 超過 7 天鑑賞期:在您收到商品 7 天鑑賞期內(非試用期)有任何問題,請於上班時間與我們聯

絡。超過 7 天鑑賞期恕無法退換貨。

2) 商品已拆封:此為私人消耗性產品,除商品本身有瑕疵可退貨外,一經拆封、使用或保存不

良導致變質,將會影響退貨權限。

■ 退款方式

信用卡:經商品退回確認在退貨權限內無誤後, 將通知原刷卡銀行進行刷退。

實際刷退時間已刷卡銀行作業時間為準。

3.
![image](https://cloud.githubusercontent.com/assets/4414580/6429749/c7c0e902-c021-11e4-9efa-dfeea9a811e3.png)

紅利點數的累積說明:購物結帳總售價(不包含運費)可換取的點數

消費 5 千元以下,100 元可換得 1 點數;

消費 5 千元~1 萬元,80 元可換得 1 點數;

消費 1 萬元~1 萬 5 千元,70 元可換得 1 點數;

消費 1 萬 5 千元以上,60 元可換得 1 點數。

**Comment by maysheena** [comment]
好囉～
