### ISSUE TITLE
產品可使用單位

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/psyche#96]
![image](https://cloud.githubusercontent.com/assets/4414580/6656162/e3b059d4-cb59-11e4-87a8-5cf3ca2911dd.png)

**Comment by maysheena** [comment]
我已經有放入欄位進去囉！

![2015-03-16 15 23 47 2](https://cloud.githubusercontent.com/assets/11195240/6661988/9e4a8530-cbf0-11e4-975c-17d1ef595834.png)
